function buildAccident(){
  const car=createCar(0x7f322c);car.position.copy(ACCIDENT_POS).add(new THREE.Vector3(2.5,0,-.7));car.rotation.y=.45;scene.add(car);
  const bike=new THREE.Group();for(const x of [-.65,.65])mesh(new THREE.TorusGeometry(.38,.045,8,20),material(0x111111),[x,.38,0],[Math.PI/2,0,0],bike);cyl(.035,1.15,0xa63229,[0,.48,0],[0,0,Math.PI/2],bike);bike.position.copy(ACCIDENT_POS).add(new THREE.Vector3(-1.6,.02,.8));bike.rotation.set(.1,.35,.45);scene.add(bike);
  [[-3,-2],[-1,-3],[2,-3]].forEach(([x,z])=>{const g=new THREE.Group();mesh(new THREE.ConeGeometry(.23,.62,10),material(0xd45c24),[0,.34,0],undefined,g);box([.55,.05,.55],0x202020,[0,.04,0],undefined,g);g.position.copy(ACCIDENT_POS).add(new THREE.Vector3(x,0,z));scene.add(g);});
  for(let i=0;i<9;i++)box([rand(.05,.18),rand(.03,.08),rand(.05,.18)],0x4d4b48,[ACCIDENT_POS.x+rand(-2,2),.05,ACCIDENT_POS.z+rand(-1.5,1.5)],[rand(0,.5),rand(0,3),rand(0,.5)]);
  patient.anchor=new THREE.Group();patient.anchor.position.copy(ACCIDENT_POS).add(new THREE.Vector3(-.1,.05,1.2));patient.anchor.rotation.z=-Math.PI/2;scene.add(patient.anchor);patient.visual=createFallbackHuman(0x343c43);patient.anchor.add(patient.visual);
  const stainMat=new THREE.MeshStandardMaterial({color:0x5f1715,roughness:1,transparent:true,opacity:.86});patient.pool=mesh(new THREE.CircleGeometry(.55,24),stainMat,[ACCIDENT_POS.x-.9,.017,ACCIDENT_POS.z+1.2],[-Math.PI/2,0,0]);
  const patchMat=new THREE.MeshBasicMaterial({color:0x731d19,transparent:true,opacity:.9,depthTest:true});patient.patch=mesh(new THREE.PlaneGeometry(.38,.22),patchMat,[0,.34,.18],[0,0,0],patient.anchor);
  const zones=[['head',1.65],['neck',1.43],['chest',1.15],['abdomen',.93],['pelvis',.72],['limbs',.38],['back',1.08]];zones.forEach(([name,y])=>{const z=mesh(new THREE.BoxGeometry(name==='limbs'?.65:.45,name==='limbs'?.55:.28,.55),new THREE.MeshBasicMaterial({transparent:true,opacity:0,depthWrite:false}),[0,y,name==='back'?-.28:0],[0,0,0],patient.anchor);z.userData.region=name;clinicalZones.push(z);});
  const pts=[[-3,3],[-4,1],[-3,-1],[4,2],[4,-1],[2,4]];pts.forEach(p=>{const r=new THREE.Group();r.add(createFallbackHuman(0x5c6166));r.position.copy(ACCIDENT_POS).add(new THREE.Vector3(p[0],0,p[1]));r.lookAt(patient.anchor.position);scene.add(r);curiosos.push(r);});
}
function bindInput(){
  $('#startShift').onclick=()=>init();$('#acceptCall').onclick=()=>{dispatchModal.hidden=true;phase='TO_AMBULANCE';setObjective('OCORRÊNCIA ACEITA','Entre na ambulância Re.Force e desloque-se para a ocorrência.');logEvent('Ocorrência aceita pela unidade.');flash('GPS atualizado: Av. Central × Rua 4');};$('#closeInteraction').onclick=()=>closeInteraction();
  $('#cameraReset').onclick=()=>{if(controlled==='vehicle')cameraYaw=-ambulance.heading;else cameraYaw=player.root.rotation.y-Math.PI;cameraPitch=.32;lastCameraDrag=0;cameraReady=false;};
  sirenBtn.onclick=()=>{ambulance.siren=!ambulance.siren;setSirenAudio(ambulance.siren);sirenBtn.classList.toggle('on',ambulance.siren);sirenBtn.textContent=ambulance.siren?'SIRENE ON':'SIRENE';};actionBtn.onclick=doContextAction;
  runBtn.addEventListener('pointerdown',e=>{e.preventDefault();runHeld=true;});['pointerup','pointercancel','pointerleave'].forEach(ev=>runBtn.addEventListener(ev,()=>runHeld=false));
  const joyMove=e=>{if(!joy.active||e.pointerId!==joy.id)return;const r=joystick.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2;let dx=e.clientX-cx,dy=e.clientY-cy;const max=r.width*.34,mag=Math.hypot(dx,dy)||1;if(mag>max){dx=dx/mag*max;dy=dy/mag*max;}joy.x=dx/max;joy.y=dy/max;stick.style.transform=`translate(${dx}px,${dy}px)`;};
  joystick.addEventListener('pointerdown',e=>{joy.active=true;joy.id=e.pointerId;joystick.setPointerCapture?.(e.pointerId);joyMove(e);});joystick.addEventListener('pointermove',joyMove);const joyEnd=e=>{if(e.pointerId!==joy.id)return;joy={x:0,y:0,active:false,id:null};stick.style.transform='translate(0,0)';};joystick.addEventListener('pointerup',joyEnd);joystick.addEventListener('pointercancel',joyEnd);
  canvas.addEventListener('pointerdown',e=>{if(uiBlock())return;cameraPointer={id:e.pointerId,x:e.clientX,y:e.clientY};canvas.setPointerCapture?.(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(!cameraPointer||e.pointerId!==cameraPointer.id||uiBlock())return;const dx=e.clientX-cameraPointer.x,dy=e.clientY-cameraPointer.y;cameraPointer.x=e.clientX;cameraPointer.y=e.clientY;cameraYaw-=dx*.0062;cameraPitch=clamp(cameraPitch-dy*.0042,.16,.82);lastCameraDrag=performance.now();});const camEnd=e=>{if(cameraPointer?.id===e.pointerId)cameraPointer=null;};canvas.addEventListener('pointerup',camEnd);canvas.addEventListener('pointercancel',camEnd);canvas.addEventListener('wheel',e=>{cameraDistance=clamp(cameraDistance+Math.sign(e.deltaY)*.6,4.5,11);},{passive:true});
  addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='KeyE')doContextAction();if(e.code==='KeyQ'){ambulance.siren=!ambulance.siren;setSirenAudio(ambulance.siren);sirenBtn.classList.toggle('on',ambulance.siren);}});addEventListener('keyup',e=>keys[e.code]=false);$('#saveGlasgow').onclick=saveGlasgow;$('#restartBtn').onclick=()=>location.reload();
}
function resize(){renderer?.setSize(innerWidth,innerHeight,false);if(camera){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();}}
function loop(){const dt=Math.min(clock.getDelta(),.05);update(dt);renderer.render(scene,camera);drawMinimap();requestAnimationFrame(loop);}
function update(dt){cityClock+=dt;updateTrafficLights();updateTraffic(dt);updatePedestrians(dt);updatePatient(dt);if(!uiBlock()&&!bodyZoneMode){if(controlled==='player')updatePlayer(dt);else updateVehicle(dt);}updateCamera(dt);updateContext();updateDistrict();trafficCollisionCooldown=Math.max(0,trafficCollisionCooldown-dt);if(ambulance.lightbar){const pulse=Math.sin(performance.now()*.018)>0;ambulance.lightbar.children[0].material.emissive=new THREE.Color(pulse&&ambulance.siren?0xff0000:0x000000);ambulance.lightbar.children[1].material.emissive=new THREE.Color(!pulse&&ambulance.siren?0x0055ff:0x000000);ambulance.lightbar.children[0].material.emissiveIntensity=2;ambulance.lightbar.children[1].material.emissiveIntensity=2;}updateSirenAudio(performance.now()*.001);}
function inputAxes(){let x=joy.x,y=joy.y;if(keys.KeyA)x=-1;if(keys.KeyD)x=1;if(keys.KeyW)y=-1;if(keys.KeyS)y=1;return{x,y};}